name: CI/CD
# using two jobs, just to preactice github actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t covid-19-nds-lambda .

      - name: Save Docker image to file
        run: docker save covid-19-nds-lambda:latest | gzip > covid-19-nds-lambda-image.tar.gz

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: covid-19-nds-lambda-image
          path: covid-19-nds-lambda-image.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: covid-19-nds-lambda-image

      - name: Load Docker image from file
        run: docker load --input covid-19-nds-lambda-image.tar.gz

      - name: Tag and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: covid-19-nds-lambda
        run: |
          docker tag covid-19-nds-lambda:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Delete Docker image artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: covid-19-nds-lambda-image
